[functions]
  external_node_modules = ["express", "pg-query-stream", "better-sqlite3", "oracledb", "mysql2", "pg", "sqlite3", "tedious", ""]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"
[[redirects]]
  force = true
  from = "/storage/uploads/products/*"
  to = "/storage/:splat"
  status = 200