[functions]
  external_node_modules = ["express", "pg-query-stream", "better-sqlite3", "oracledb", "mysql2", "pg", "sqlite3", "tedious", ""]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/swagger/*"
  status = 200
  to = "/.netlify/functions/swagger/:splat"